<?php

namespace Acme\StoreBundle\Repository;

use Acme\StoreBundle\Document\Category;
use Acme\StoreBundle\Document\Product;
use Doctrine\ODM\MongoDB\DocumentRepository;
use Acme\StoreBundle\Repository\CategoryRepository;
/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends DocumentRepository
{



    public function findAllOrderedByName()
    {
        return $this->createQueryBuilder()
            ->sort('name', 'ASC')
            ->getQuery()
            ->execute();
    }


    public function updateProductsCategoryField(Category $category)
    {



        /*        $cat = $this->createQueryBuilder('Category')
                    ->field('name')->equals('choisissez une catégorie')
                    ->hydrate(false)
                    ->refresh()
                    ->getQuery()
                    ->getSingleResult();*/



        return $this->createQueryBuilder('Product')
            ->findAndUpdate()
            ->field('categorie')->set(null)
            ->field('categorie')->references($category)
            ->getQuery()
            ->execute();


        /*return $this->createQueryBuilder('Product')
            ->update()
            ->field('categorie')->set('')
            ->field('categorie')->references($category)
            ->getQuery()
            ->execute();*/
    }











}